# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_startWindow(object):
    def setupUiStart(self, startWindow):
        startWindow.setObjectName("startWindow")
        startWindow.resize(450, 200)
        font = QtGui.QFont()
        font.setPointSize(10)
        startWindow.setFont(font)


        self.centralwidget = QtWidgets.QWidget(startWindow)
        self.centralwidget.setObjectName("centralwidget")





        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")


        self.pushButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonAdd.setAutoDefault(True)
        self.pushButtonAdd.setDefault(False)
        self.pushButtonAdd.setFlat(False)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout.addWidget(self.pushButtonAdd, 0, 0, 1, 1)
        self.pushButtonView = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonView.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButtonView.setAutoDefault(True)
        self.pushButtonView.setDefault(False)
        self.pushButtonView.setFlat(False)
        self.pushButtonView.setObjectName("pushButtonView")
        self.gridLayout.addWidget(self.pushButtonView, 1, 0, 1, 1)
        startWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(startWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 29))
        self.menubar.setObjectName("menubar")
        startWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(startWindow)
        self.statusbar.setObjectName("statusbar")
        startWindow.setStatusBar(self.statusbar)

        self.retranslateUi(startWindow)
        QtCore.QMetaObject.connectSlotsByName(startWindow)

    def retranslateUi(self, startWindow):

        _translate = QtCore.QCoreApplication.translate
        startWindow.setWindowTitle(_translate("startWindow", "Выберите необходимое действие"))
        self.pushButtonAdd.setText(_translate("startWindow", "Добавить"))
        self.pushButtonView.setText(_translate("startWindow", "Просмотр"))
