# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewAllServices.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewAllServices(object):
    def setupUiView(self, viewAllServices):
        viewAllServices.setObjectName("viewAllServices")
        viewAllServices.resize(933, 642)
        self.centralwidget = QtWidgets.QWidget(viewAllServices)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.tableWidget.hideColumn(10)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.pushButtonSearch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.gridLayout.addWidget(self.pushButtonSearch, 3, 0, 1, 1)
        viewAllServices.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(viewAllServices)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 26))
        self.menubar.setObjectName("menubar")
        viewAllServices.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(viewAllServices)
        self.statusbar.setObjectName("statusbar")
        viewAllServices.setStatusBar(self.statusbar)

        self.retranslateUiView(viewAllServices)
        QtCore.QMetaObject.connectSlotsByName(viewAllServices)

    def retranslateUiView(self, viewAllServices):

        _translate = QtCore.QCoreApplication.translate
        viewAllServices.setWindowTitle(_translate("viewAllServices", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("viewAllServices", "Статус"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("viewAllServices", "Съёмка"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("viewAllServices", "Населенный пункт"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("viewAllServices", "Адрес"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("viewAllServices", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("viewAllServices", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("viewAllServices", "Отчество"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("viewAllServices", "Номер телефона"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("viewAllServices", "Дата записи"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("viewAllServices", "Услуга"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("viewAllServices", "№"))




        self.label.setText(_translate("viewAllServices", "Поиск"))
        self.comboBox.setItemText(0, _translate("viewAllServices", "Услуга"))
        self.comboBox.setItemText(1, _translate("viewAllServices", "Населенный пункт"))
        self.comboBox.setItemText(2, _translate("viewAllServices", "Фамилия"))
        self.comboBox.setItemText(3, _translate("viewAllServices", "Статус"))
        self.pushButtonSearch.setText(_translate("viewAllServices", "Поиск"))
