# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewSelectFormUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewSelectFormUi(object):
    def setupUi(self, viewSelectFormUi):
        viewSelectFormUi.setObjectName("viewSelectFormUi")
        viewSelectFormUi.resize(500, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(viewSelectFormUi.sizePolicy().hasHeightForWidth())
        viewSelectFormUi.setSizePolicy(sizePolicy)
        viewSelectFormUi.setMinimumSize(QtCore.QSize(500, 750))
        viewSelectFormUi.setMaximumSize(QtCore.QSize(500, 750))
        font = QtGui.QFont()
        font.setPointSize(10)
        viewSelectFormUi.setFont(font)
        viewSelectFormUi.setStyleSheet("/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #a3a3a3;\n"
"    color: #3a3a3d;\n"
"    selection-background-color: #3a3a3d;\n"
"    selection-color: #3a3a3d;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    padding: 3px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: rgba(70,162,218,50%);\n"
"    border: 1px solid #46a2da;\n"
"    color: #000;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #222;\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #bdbdbd;\n"
"    color: #3a3a3d;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #606060;\n"
"    color: #959595;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #707070;\n"
"    border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #bdbdbd;\n"
"    border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    background-color: #707070;\n"
"    border: 1px solid #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    color: #3a3a3d;\n"
"    border: 1px solid #f0f0f0;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTExtEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    color : #fff;\n"
"    border: 1px solid #f0f0f0;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"QTextEdit\n"
"{\n"
"    color: #3a3a3d;\n"
"    background-color: #f5f5f5;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"/*-----QToolBox-----*/\n"
"QToolBox\n"
"{\n"
"    background-color: transparent;\n"
"    border: 1px solid #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: #006d6d;\n"
"    border: 1px solid #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: #f5f5f5;\n"
"    padding-left: 6px;\n"
"    color: #3a3a3d;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #f0f0f0;\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    border: 0px; /* This seems to replace the whole arrow of the combo box */\n"
"    background-color: #lightgray;\n"
"}\n"
"\n"
"/* Define a new custom arrow icon for the combo box */\n"
"QComboBox::down-arrow {\n"
"    background-color: #lightgray;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #575757;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"    selection-background-color: #002b2b;\n"
"    selection-color: #fff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    background-color: #4a5157;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 4px;\n"
"    width: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QDateEdit\n"
"{\n"
"        color: #3a3a3d;\n"
"        background-color: #f5f5f5;\n"
"        border: 1px solid #f0f0f0;\n"
"        border-radius: 4px;\n"
"}\n"
"QLabel\n"
"{\n"
"        color: #3a3a3d;\n"
"}\n"
"QDateTimeEdit\n"
"{\n"
"        background-color: #f5f5f5;\n"
"}\n"
"\n"
"/*-----QHeaderView-----*/\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: none;\n"
"    color: #fff;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"QFont\n"
"{\n"
"        background-color: #3a3a3d;\n"
"}\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCalendarWidget-----*/\n"
"QCalendarWidget QToolButton\n"
"{\n"
"      background-color: transparent;\n"
"      color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QToolButton::hover\n"
"{\n"
"    background-color: #006666;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu \n"
"{\n"
"    width: 120px;\n"
"    left: 20px;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QWidget \n"
"{ \n"
"    alternate-background-color: #4a5157; \n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    color: #fff;  \n"
"    background-color: #a0a0a3;  \n"
"    selection-background-color: #d4d4d4; \n"
"    selection-color: #fff; \n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"    color: #404040; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeView\n"
"{\n"
"    show-decoration-selected: 0;\n"
"    alternate-background-color: transparent;\n"
"    background-color: transparent;\n"
"       border: none;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#fff;\n"
"    background-color: #002b2b;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    border : none;\n"
"    color: #fff;\n"
"    show-decoration-selected: 1; \n"
"    outline: 0;\n"
"       border: 1px solid #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    background-color: transparent;\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: lightgray;\n"
"    border: 1px solid #000;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #3a546e;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #46a2da; \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton \n"
"{\n"
"    color: #fff;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover \n"
"{\n"
"    background-color: #d3d3d3;\n"
"    border: 2px solid #002b2b;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    border: 2px solid #52beff;\n"
"    border-radius: 6px;\n"
"    background-color: #002b2b;  \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:vertical \n"
"{\n"
"   border: none;\n"
"   width: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   width : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal \n"
"{\n"
"   border: none;\n"
"   height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   height : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:horizontal\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:horizontal \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(viewSelectFormUi)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEditPassport = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditPassport.sizePolicy().hasHeightForWidth())
        self.textEditPassport.setSizePolicy(sizePolicy)
        self.textEditPassport.setMinimumSize(QtCore.QSize(350, 80))
        self.textEditPassport.setMaximumSize(QtCore.QSize(355, 80))
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEditPassport.setFont(font)
        self.textEditPassport.setObjectName("textEditPassport")
        self.gridLayout.addWidget(self.textEditPassport, 25, 1, 1, 1)
        self.lineEditSurname = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSurname.setFont(font)
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.gridLayout.addWidget(self.lineEditSurname, 4, 1, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditName.setFont(font)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout.addWidget(self.lineEditName, 6, 1, 1, 1)
        self.lineEditMiddleName = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditMiddleName.setFont(font)
        self.lineEditMiddleName.setObjectName("lineEditMiddleName")
        self.gridLayout.addWidget(self.lineEditMiddleName, 8, 1, 1, 1)
        self.lineEditPrice = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPrice.setFont(font)
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.gridLayout.addWidget(self.lineEditPrice, 14, 1, 1, 1)
        self.comboBoxStatus = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxStatus.setFont(font)
        self.comboBoxStatus.setObjectName("comboBoxStatus")
        self.comboBoxStatus.addItem("")
        self.comboBoxStatus.addItem("")
        self.comboBoxStatus.addItem("")
        self.gridLayout.addWidget(self.comboBoxStatus, 16, 1, 1, 1)
        self.lineEditSnils = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSnils.setFont(font)
        self.lineEditSnils.setText("")
        self.lineEditSnils.setMaxLength(14)
        self.lineEditSnils.setObjectName("lineEditSnils")
        self.gridLayout.addWidget(self.lineEditSnils, 24, 1, 1, 1)
        self.dateEditDate = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEditDate.setFont(font)
        self.dateEditDate.setCalendarPopup(True)
        self.dateEditDate.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEditDate.setObjectName("dateEditDate")
        self.gridLayout.addWidget(self.dateEditDate, 12, 1, 1, 1)
        self.lineEditTelefone = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditTelefone.setFont(font)
        self.lineEditTelefone.setObjectName("lineEditTelefone")
        self.gridLayout.addWidget(self.lineEditTelefone, 10, 1, 1, 1)
        self.dateEditDataWork = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateEditDataWork.setFont(font)
        self.dateEditDataWork.setCalendarPopup(True)
        self.dateEditDataWork.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEditDataWork.setObjectName("dateEditDataWork")
        self.gridLayout.addWidget(self.dateEditDataWork, 20, 1, 1, 1)
        self.comboBoxWork = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxWork.setFont(font)
        self.comboBoxWork.setObjectName("comboBoxWork")
        self.comboBoxWork.addItem("")
        self.comboBoxWork.addItem("")
        self.comboBoxWork.addItem("")
        self.gridLayout.addWidget(self.comboBoxWork, 18, 1, 1, 1)
        self.checkBoxDeclaration = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxDeclaration.setFont(font)
        self.checkBoxDeclaration.setObjectName("checkBoxDeclaration")
        self.gridLayout.addWidget(self.checkBoxDeclaration, 30, 0, 1, 1)
        self.checkBoxConsent = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxConsent.setFont(font)
        self.checkBoxConsent.setObjectName("checkBoxConsent")
        self.gridLayout.addWidget(self.checkBoxConsent, 31, 0, 1, 1)
        self.checkBoxAct = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxAct.setFont(font)
        self.checkBoxAct.setObjectName("checkBoxAct")
        self.gridLayout.addWidget(self.checkBoxAct, 32, 0, 1, 1)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 6, 0, 1, 1)
        self.labelSurname = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSurname.setFont(font)
        self.labelSurname.setObjectName("labelSurname")
        self.gridLayout.addWidget(self.labelSurname, 4, 0, 1, 1)
        self.labelDataWork = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDataWork.setFont(font)
        self.labelDataWork.setObjectName("labelDataWork")
        self.gridLayout.addWidget(self.labelDataWork, 20, 0, 1, 1)
        self.labelTelefone = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTelefone.setFont(font)
        self.labelTelefone.setObjectName("labelTelefone")
        self.gridLayout.addWidget(self.labelTelefone, 10, 0, 1, 1)
        self.labelMiddleName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelMiddleName.setFont(font)
        self.labelMiddleName.setObjectName("labelMiddleName")
        self.gridLayout.addWidget(self.labelMiddleName, 8, 0, 1, 1)
        self.labelSnils = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSnils.setFont(font)
        self.labelSnils.setObjectName("labelSnils")
        self.gridLayout.addWidget(self.labelSnils, 24, 0, 1, 1)
        self.labelPrice = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrice.setFont(font)
        self.labelPrice.setObjectName("labelPrice")
        self.gridLayout.addWidget(self.labelPrice, 14, 0, 1, 1)
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelInfo.setFont(font)
        self.labelInfo.setObjectName("labelInfo")
        self.gridLayout.addWidget(self.labelInfo, 22, 0, 1, 1)
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout.addWidget(self.labelDate, 12, 0, 1, 1)
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStatus.setFont(font)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 16, 0, 1, 1)
        self.labelPassport = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassport.setFont(font)
        self.labelPassport.setObjectName("labelPassport")
        self.gridLayout.addWidget(self.labelPassport, 25, 0, 1, 1)
        self.labelWork = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelWork.setFont(font)
        self.labelWork.setObjectName("labelWork")
        self.gridLayout.addWidget(self.labelWork, 18, 0, 1, 1)
        self.textEditInfo = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditInfo.sizePolicy().hasHeightForWidth())
        self.textEditInfo.setSizePolicy(sizePolicy)
        self.textEditInfo.setMinimumSize(QtCore.QSize(350, 80))
        self.textEditInfo.setMaximumSize(QtCore.QSize(350, 80))
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textEditInfo.setFont(font)
        self.textEditInfo.setObjectName("textEditInfo")
        self.gridLayout.addWidget(self.textEditInfo, 22, 1, 1, 1)
        self.pushButtonOpenFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOpenFolder.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenFolder.setFont(font)
        self.pushButtonOpenFolder.setObjectName("pushButtonOpenFolder")
        self.gridLayout.addWidget(self.pushButtonOpenFolder, 33, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Kartika")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 35, 0, 1, 2)
        viewSelectFormUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(viewSelectFormUi)
        QtCore.QMetaObject.connectSlotsByName(viewSelectFormUi)
        viewSelectFormUi.setTabOrder(self.lineEditSurname, self.lineEditName)
        viewSelectFormUi.setTabOrder(self.lineEditName, self.lineEditMiddleName)
        viewSelectFormUi.setTabOrder(self.lineEditMiddleName, self.lineEditTelefone)
        viewSelectFormUi.setTabOrder(self.lineEditTelefone, self.dateEditDate)
        viewSelectFormUi.setTabOrder(self.dateEditDate, self.lineEditPrice)
        viewSelectFormUi.setTabOrder(self.lineEditPrice, self.comboBoxStatus)
        viewSelectFormUi.setTabOrder(self.comboBoxStatus, self.comboBoxWork)
        viewSelectFormUi.setTabOrder(self.comboBoxWork, self.dateEditDataWork)
        viewSelectFormUi.setTabOrder(self.dateEditDataWork, self.textEditInfo)
        viewSelectFormUi.setTabOrder(self.textEditInfo, self.lineEditSnils)
        viewSelectFormUi.setTabOrder(self.lineEditSnils, self.textEditPassport)
        viewSelectFormUi.setTabOrder(self.textEditPassport, self.checkBoxDeclaration)
        viewSelectFormUi.setTabOrder(self.checkBoxDeclaration, self.checkBoxConsent)
        viewSelectFormUi.setTabOrder(self.checkBoxConsent, self.checkBoxAct)

    def retranslateUi(self, viewSelectFormUi):
        _translate = QtCore.QCoreApplication.translate
        viewSelectFormUi.setWindowTitle(_translate("viewSelectFormUi", "Просмотр/изменение данных"))
        self.textEditPassport.setPlaceholderText(_translate("viewSelectFormUi", "Когда? Кем? "))
        self.lineEditPrice.setPlaceholderText(_translate("viewSelectFormUi", "8000"))
        self.comboBoxStatus.setItemText(0, _translate("viewSelectFormUi", "Готова"))
        self.comboBoxStatus.setItemText(1, _translate("viewSelectFormUi", "Ожидание"))
        self.comboBoxStatus.setItemText(2, _translate("viewSelectFormUi", "Разработка"))
        self.lineEditSnils.setPlaceholderText(_translate("viewSelectFormUi", "111-111-111 11"))
        self.lineEditTelefone.setPlaceholderText(_translate("viewSelectFormUi", "89216734503"))
        self.comboBoxWork.setItemText(0, _translate("viewSelectFormUi", "Ожидает выезд"))
        self.comboBoxWork.setItemText(1, _translate("viewSelectFormUi", "В обработке"))
        self.comboBoxWork.setItemText(2, _translate("viewSelectFormUi", "Готова"))
        self.checkBoxDeclaration.setText(_translate("viewSelectFormUi", "Декларация"))
        self.checkBoxConsent.setText(_translate("viewSelectFormUi", "Согласие"))
        self.checkBoxAct.setText(_translate("viewSelectFormUi", "АКТ"))
        self.labelName.setText(_translate("viewSelectFormUi", "Имя"))
        self.labelSurname.setText(_translate("viewSelectFormUi", "Фамилия"))
        self.labelDataWork.setText(_translate("viewSelectFormUi", "Дата съёмки"))
        self.labelTelefone.setText(_translate("viewSelectFormUi", "Номер телефона"))
        self.labelMiddleName.setText(_translate("viewSelectFormUi", "Отчество"))
        self.labelSnils.setText(_translate("viewSelectFormUi", "СНИЛС"))
        self.labelPrice.setText(_translate("viewSelectFormUi", "Стоимость"))
        self.labelInfo.setText(_translate("viewSelectFormUi", "Доп. Информация"))
        self.labelDate.setText(_translate("viewSelectFormUi", "Дата записи"))
        self.labelStatus.setText(_translate("viewSelectFormUi", "Статус"))
        self.labelPassport.setText(_translate("viewSelectFormUi", "Паспорт"))
        self.labelWork.setText(_translate("viewSelectFormUi", "Съёмка"))
        self.textEditInfo.setPlaceholderText(_translate("viewSelectFormUi", "Особые заметки"))
        self.pushButtonOpenFolder.setText(_translate("viewSelectFormUi", "Открыть папку"))
        self.pushButton.setText(_translate("viewSelectFormUi", "Изменить данные"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewSelectFormUi = QtWidgets.QMainWindow()
    ui = Ui_viewSelectFormUi()
    ui.setupUi(viewSelectFormUi)
    viewSelectFormUi.show()
    sys.exit(app.exec_())
